// Code generated by MockGen. DO NOT EDIT.
// Source: secret_save.go
//
// Generated by this command:
//
//	mockgen -source=secret_save.go -destination=mocks/secret_save.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	query "gophkeeper/internal/server/infra/db/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocksecretFinder is a mock of secretFinder interface.
type MocksecretFinder struct {
	ctrl     *gomock.Controller
	recorder *MocksecretFinderMockRecorder
	isgomock struct{}
}

// MocksecretFinderMockRecorder is the mock recorder for MocksecretFinder.
type MocksecretFinderMockRecorder struct {
	mock *MocksecretFinder
}

// NewMocksecretFinder creates a new mock instance.
func NewMocksecretFinder(ctrl *gomock.Controller) *MocksecretFinder {
	mock := &MocksecretFinder{ctrl: ctrl}
	mock.recorder = &MocksecretFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretFinder) EXPECT() *MocksecretFinderMockRecorder {
	return m.recorder
}

// FindSecret mocks base method.
func (m *MocksecretFinder) FindSecret(ctx context.Context, arg query.FindSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSecret indicates an expected call of FindSecret.
func (mr *MocksecretFinderMockRecorder) FindSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSecret", reflect.TypeOf((*MocksecretFinder)(nil).FindSecret), ctx, arg)
}

// MocksecretCreator is a mock of secretCreator interface.
type MocksecretCreator struct {
	ctrl     *gomock.Controller
	recorder *MocksecretCreatorMockRecorder
	isgomock struct{}
}

// MocksecretCreatorMockRecorder is the mock recorder for MocksecretCreator.
type MocksecretCreatorMockRecorder struct {
	mock *MocksecretCreator
}

// NewMocksecretCreator creates a new mock instance.
func NewMocksecretCreator(ctrl *gomock.Controller) *MocksecretCreator {
	mock := &MocksecretCreator{ctrl: ctrl}
	mock.recorder = &MocksecretCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretCreator) EXPECT() *MocksecretCreatorMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MocksecretCreator) CreateSecret(ctx context.Context, arg query.CreateSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MocksecretCreatorMockRecorder) CreateSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MocksecretCreator)(nil).CreateSecret), ctx, arg)
}

// MocksecretUpdater is a mock of secretUpdater interface.
type MocksecretUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocksecretUpdaterMockRecorder
	isgomock struct{}
}

// MocksecretUpdaterMockRecorder is the mock recorder for MocksecretUpdater.
type MocksecretUpdaterMockRecorder struct {
	mock *MocksecretUpdater
}

// NewMocksecretUpdater creates a new mock instance.
func NewMocksecretUpdater(ctrl *gomock.Controller) *MocksecretUpdater {
	mock := &MocksecretUpdater{ctrl: ctrl}
	mock.recorder = &MocksecretUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretUpdater) EXPECT() *MocksecretUpdaterMockRecorder {
	return m.recorder
}

// UpdateSecret mocks base method.
func (m *MocksecretUpdater) UpdateSecret(ctx context.Context, arg query.UpdateSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MocksecretUpdaterMockRecorder) UpdateSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MocksecretUpdater)(nil).UpdateSecret), ctx, arg)
}

// MocksecretDeleter is a mock of secretDeleter interface.
type MocksecretDeleter struct {
	ctrl     *gomock.Controller
	recorder *MocksecretDeleterMockRecorder
	isgomock struct{}
}

// MocksecretDeleterMockRecorder is the mock recorder for MocksecretDeleter.
type MocksecretDeleterMockRecorder struct {
	mock *MocksecretDeleter
}

// NewMocksecretDeleter creates a new mock instance.
func NewMocksecretDeleter(ctrl *gomock.Controller) *MocksecretDeleter {
	mock := &MocksecretDeleter{ctrl: ctrl}
	mock.recorder = &MocksecretDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretDeleter) EXPECT() *MocksecretDeleterMockRecorder {
	return m.recorder
}

// DeleteSecret mocks base method.
func (m *MocksecretDeleter) DeleteSecret(ctx context.Context, arg query.DeleteSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MocksecretDeleterMockRecorder) DeleteSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MocksecretDeleter)(nil).DeleteSecret), ctx, arg)
}

// MocksecretRepository is a mock of secretRepository interface.
type MocksecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksecretRepositoryMockRecorder
	isgomock struct{}
}

// MocksecretRepositoryMockRecorder is the mock recorder for MocksecretRepository.
type MocksecretRepositoryMockRecorder struct {
	mock *MocksecretRepository
}

// NewMocksecretRepository creates a new mock instance.
func NewMocksecretRepository(ctrl *gomock.Controller) *MocksecretRepository {
	mock := &MocksecretRepository{ctrl: ctrl}
	mock.recorder = &MocksecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretRepository) EXPECT() *MocksecretRepositoryMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MocksecretRepository) CreateSecret(ctx context.Context, arg query.CreateSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MocksecretRepositoryMockRecorder) CreateSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MocksecretRepository)(nil).CreateSecret), ctx, arg)
}

// DeleteSecret mocks base method.
func (m *MocksecretRepository) DeleteSecret(ctx context.Context, arg query.DeleteSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MocksecretRepositoryMockRecorder) DeleteSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MocksecretRepository)(nil).DeleteSecret), ctx, arg)
}

// FindSecret mocks base method.
func (m *MocksecretRepository) FindSecret(ctx context.Context, arg query.FindSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSecret indicates an expected call of FindSecret.
func (mr *MocksecretRepositoryMockRecorder) FindSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSecret", reflect.TypeOf((*MocksecretRepository)(nil).FindSecret), ctx, arg)
}

// UpdateSecret mocks base method.
func (m *MocksecretRepository) UpdateSecret(ctx context.Context, arg query.UpdateSecretParams) (query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, arg)
	ret0, _ := ret[0].(query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MocksecretRepositoryMockRecorder) UpdateSecret(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MocksecretRepository)(nil).UpdateSecret), ctx, arg)
}
