// Code generated by MockGen. DO NOT EDIT.
// Source: secret_list.go
//
// Generated by this command:
//
//	mockgen -source=secret_list.go -destination=mocks/secret_list.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	query "gophkeeper/internal/server/infra/db/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocksecretLister is a mock of secretLister interface.
type MocksecretLister struct {
	ctrl     *gomock.Controller
	recorder *MocksecretListerMockRecorder
	isgomock struct{}
}

// MocksecretListerMockRecorder is the mock recorder for MocksecretLister.
type MocksecretListerMockRecorder struct {
	mock *MocksecretLister
}

// NewMocksecretLister creates a new mock instance.
func NewMocksecretLister(ctrl *gomock.Controller) *MocksecretLister {
	mock := &MocksecretLister{ctrl: ctrl}
	mock.recorder = &MocksecretListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksecretLister) EXPECT() *MocksecretListerMockRecorder {
	return m.recorder
}

// ListSecrets mocks base method.
func (m *MocksecretLister) ListSecrets(ctx context.Context, userID int64) ([]query.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx, userID)
	ret0, _ := ret[0].([]query.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MocksecretListerMockRecorder) ListSecrets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MocksecretLister)(nil).ListSecrets), ctx, userID)
}
