// Code generated by MockGen. DO NOT EDIT.
// Source: user_find.go
//
// Generated by this command:
//
//	mockgen -source=user_find.go -destination=mocks/user_find.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	query "gophkeeper/internal/server/infra/db/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuserFinderByID is a mock of userFinderByID interface.
type MockuserFinderByID struct {
	ctrl     *gomock.Controller
	recorder *MockuserFinderByIDMockRecorder
	isgomock struct{}
}

// MockuserFinderByIDMockRecorder is the mock recorder for MockuserFinderByID.
type MockuserFinderByIDMockRecorder struct {
	mock *MockuserFinderByID
}

// NewMockuserFinderByID creates a new mock instance.
func NewMockuserFinderByID(ctrl *gomock.Controller) *MockuserFinderByID {
	mock := &MockuserFinderByID{ctrl: ctrl}
	mock.recorder = &MockuserFinderByIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserFinderByID) EXPECT() *MockuserFinderByIDMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *MockuserFinderByID) GetUserById(ctx context.Context, id int64) (query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockuserFinderByIDMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockuserFinderByID)(nil).GetUserById), ctx, id)
}
