// Code generated by MockGen. DO NOT EDIT.
// Source: user_register.go
//
// Generated by this command:
//
//	mockgen -source=user_register.go -destination=mocks/user_register.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	query "gophkeeper/internal/server/infra/db/query"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuserCreator is a mock of userCreator interface.
type MockuserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserCreatorMockRecorder
	isgomock struct{}
}

// MockuserCreatorMockRecorder is the mock recorder for MockuserCreator.
type MockuserCreatorMockRecorder struct {
	mock *MockuserCreator
}

// NewMockuserCreator creates a new mock instance.
func NewMockuserCreator(ctrl *gomock.Controller) *MockuserCreator {
	mock := &MockuserCreator{ctrl: ctrl}
	mock.recorder = &MockuserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserCreator) EXPECT() *MockuserCreatorMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockuserCreator) CreateUser(ctx context.Context, params query.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuserCreatorMockRecorder) CreateUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuserCreator)(nil).CreateUser), ctx, params)
}

// MockuserFinderByFingerprint is a mock of userFinderByFingerprint interface.
type MockuserFinderByFingerprint struct {
	ctrl     *gomock.Controller
	recorder *MockuserFinderByFingerprintMockRecorder
	isgomock struct{}
}

// MockuserFinderByFingerprintMockRecorder is the mock recorder for MockuserFinderByFingerprint.
type MockuserFinderByFingerprintMockRecorder struct {
	mock *MockuserFinderByFingerprint
}

// NewMockuserFinderByFingerprint creates a new mock instance.
func NewMockuserFinderByFingerprint(ctrl *gomock.Controller) *MockuserFinderByFingerprint {
	mock := &MockuserFinderByFingerprint{ctrl: ctrl}
	mock.recorder = &MockuserFinderByFingerprintMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserFinderByFingerprint) EXPECT() *MockuserFinderByFingerprintMockRecorder {
	return m.recorder
}

// GetUserByFingerprint mocks base method.
func (m *MockuserFinderByFingerprint) GetUserByFingerprint(ctx context.Context, fingerprint string) (query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByFingerprint", ctx, fingerprint)
	ret0, _ := ret[0].(query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByFingerprint indicates an expected call of GetUserByFingerprint.
func (mr *MockuserFinderByFingerprintMockRecorder) GetUserByFingerprint(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByFingerprint", reflect.TypeOf((*MockuserFinderByFingerprint)(nil).GetUserByFingerprint), ctx, fingerprint)
}

// MockregisterRepository is a mock of registerRepository interface.
type MockregisterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockregisterRepositoryMockRecorder
	isgomock struct{}
}

// MockregisterRepositoryMockRecorder is the mock recorder for MockregisterRepository.
type MockregisterRepositoryMockRecorder struct {
	mock *MockregisterRepository
}

// NewMockregisterRepository creates a new mock instance.
func NewMockregisterRepository(ctrl *gomock.Controller) *MockregisterRepository {
	mock := &MockregisterRepository{ctrl: ctrl}
	mock.recorder = &MockregisterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockregisterRepository) EXPECT() *MockregisterRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockregisterRepository) CreateUser(ctx context.Context, params query.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockregisterRepositoryMockRecorder) CreateUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockregisterRepository)(nil).CreateUser), ctx, params)
}

// GetUserByFingerprint mocks base method.
func (m *MockregisterRepository) GetUserByFingerprint(ctx context.Context, fingerprint string) (query.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByFingerprint", ctx, fingerprint)
	ret0, _ := ret[0].(query.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByFingerprint indicates an expected call of GetUserByFingerprint.
func (mr *MockregisterRepositoryMockRecorder) GetUserByFingerprint(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByFingerprint", reflect.TypeOf((*MockregisterRepository)(nil).GetUserByFingerprint), ctx, fingerprint)
}
