// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"time"
)

type Secret struct {
	ID        string
	UserID    int64
	Crypt     []byte
	Meta      []byte
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          int64
	Fingerprint string
	PublicKey   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
