// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: secrets.sql

package query

import (
	"context"
	"time"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (id, user_id, crypt, meta, data, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
ON CONFLICT (id, user_id) DO UPDATE SET crypt = excluded.crypt, meta = excluded.meta, data = excluded.data, updated_at = excluded.updated_at WHERE secrets.updated_at <= excluded.updated_at
RETURNING id, user_id, crypt, meta, data, created_at, updated_at
`

type CreateSecretParams struct {
	ID        string
	UserID    int64
	Crypt     []byte
	Meta      []byte
	Data      []byte
	CreatedAt time.Time
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret,
		arg.ID,
		arg.UserID,
		arg.Crypt,
		arg.Meta,
		arg.Data,
		arg.CreatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Crypt,
		&i.Meta,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :one
DELETE FROM secrets WHERE id=$1 AND user_id=$2 AND updated_at <= $3
RETURNING id, user_id, crypt, meta, data, created_at, updated_at
`

type DeleteSecretParams struct {
	ID        string
	UserID    int64
	UpdatedAt time.Time
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, deleteSecret, arg.ID, arg.UserID, arg.UpdatedAt)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Crypt,
		&i.Meta,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSecret = `-- name: FindSecret :one
SELECT id, user_id, crypt, meta, data, created_at, updated_at FROM secrets WHERE id=$1 AND user_id=$2 LIMIT 1
`

type FindSecretParams struct {
	ID     string
	UserID int64
}

func (q *Queries) FindSecret(ctx context.Context, arg FindSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, findSecret, arg.ID, arg.UserID)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Crypt,
		&i.Meta,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, user_id, crypt, meta, data, created_at, updated_at FROM secrets WHERE user_id=$1
`

func (q *Queries) ListSecrets(ctx context.Context, userID int64) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Crypt,
			&i.Meta,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET id=$1, crypt=$2, meta=$3, data=$4, updated_at=$5
WHERE id=$6 AND user_id=$7 AND updated_at <= $5
RETURNING id, user_id, crypt, meta, data, created_at, updated_at
`

type UpdateSecretParams struct {
	ID        string
	Crypt     []byte
	Meta      []byte
	Data      []byte
	UpdatedAt time.Time
	ID_2      string
	UserID    int64
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret,
		arg.ID,
		arg.Crypt,
		arg.Meta,
		arg.Data,
		arg.UpdatedAt,
		arg.ID_2,
		arg.UserID,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Crypt,
		&i.Meta,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
