// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package query

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (fingerprint, public_key, created_at, updated_at)
VALUES ($1, $2, $3, $3)
RETURNING id
`

type CreateUserParams struct {
	Fingerprint string
	PublicKey   string
	CreatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Fingerprint, arg.PublicKey, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByFingerprint = `-- name: GetUserByFingerprint :one
SELECT id, fingerprint, public_key, created_at, updated_at FROM users WHERE fingerprint=$1 LIMIT 1
`

func (q *Queries) GetUserByFingerprint(ctx context.Context, fingerprint string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFingerprint, fingerprint)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, fingerprint, public_key, created_at, updated_at FROM users WHERE id=$1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET fingerprint=$1, public_key = $2, updated_at = $3
WHERE id = $4
`

type UpdateUserParams struct {
	Fingerprint string
	PublicKey   string
	UpdatedAt   time.Time
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Fingerprint,
		arg.PublicKey,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
