// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/secret.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretAction int32

const (
	SecretAction_UNKNOWN SecretAction = 0
	SecretAction_LIST    SecretAction = 1
	SecretAction_STORED  SecretAction = 2
	SecretAction_DELETED SecretAction = 3
)

// Enum value maps for SecretAction.
var (
	SecretAction_name = map[int32]string{
		0: "UNKNOWN",
		1: "LIST",
		2: "STORED",
		3: "DELETED",
	}
	SecretAction_value = map[string]int32{
		"UNKNOWN": 0,
		"LIST":    1,
		"STORED":  2,
		"DELETED": 3,
	}
)

func (x SecretAction) Enum() *SecretAction {
	p := new(SecretAction)
	*p = x
	return p
}

func (x SecretAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_secret_proto_enumTypes[0].Descriptor()
}

func (SecretAction) Type() protoreflect.EnumType {
	return &file_api_proto_secret_proto_enumTypes[0]
}

func (x SecretAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretAction.Descriptor instead.
func (SecretAction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{0}
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_api_proto_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Auth) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Auth) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Auth) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Crypt         []byte                 `protobuf:"bytes,2,opt,name=crypt,proto3" json:"crypt,omitempty"`
	Meta          []byte                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_api_proto_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetCrypt() []byte {
	if x != nil {
		return x.Crypt
	}
	return nil
}

func (x *Secret) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Secret) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Secret) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type SecretStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Crypt         []byte                 `protobuf:"bytes,3,opt,name=crypt,proto3" json:"crypt,omitempty"`
	Meta          []byte                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	EventTime     int64                  `protobuf:"varint,6,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretStoreRequest) Reset() {
	*x = SecretStoreRequest{}
	mi := &file_api_proto_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretStoreRequest) ProtoMessage() {}

func (x *SecretStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretStoreRequest.ProtoReflect.Descriptor instead.
func (*SecretStoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{2}
}

func (x *SecretStoreRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SecretStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretStoreRequest) GetCrypt() []byte {
	if x != nil {
		return x.Crypt
	}
	return nil
}

func (x *SecretStoreRequest) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SecretStoreRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SecretStoreRequest) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type SecretDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	EventTime     int64                  `protobuf:"varint,2,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteRequest) Reset() {
	*x = SecretDeleteRequest{}
	mi := &file_api_proto_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteRequest) ProtoMessage() {}

func (x *SecretDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDeleteRequest.ProtoReflect.Descriptor instead.
func (*SecretDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{3}
}

func (x *SecretDeleteRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SecretDeleteRequest) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

type SecretEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        SecretAction           `protobuf:"varint,1,opt,name=action,proto3,enum=gophkeeper.SecretAction" json:"action,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Secret        *Secret                `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretEvent) Reset() {
	*x = SecretEvent{}
	mi := &file_api_proto_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretEvent) ProtoMessage() {}

func (x *SecretEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretEvent.ProtoReflect.Descriptor instead.
func (*SecretEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_secret_proto_rawDescGZIP(), []int{4}
}

func (x *SecretEvent) GetAction() SecretAction {
	if x != nil {
		return x.Action
	}
	return SecretAction_UNKNOWN
}

func (x *SecretEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretEvent) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_api_proto_secret_proto protoreflect.FileDescriptor

const file_api_proto_secret_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/secret.proto\x12\n" +
	"gophkeeper\"k\n" +
	"\x04Auth\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\x94\x01\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05crypt\x18\x02 \x01(\fR\x05crypt\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\fR\x04meta\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xa7\x01\n" +
	"\x12SecretStoreRequest\x12$\n" +
	"\x04auth\x18\x01 \x01(\v2\x10.gophkeeper.AuthR\x04auth\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05crypt\x18\x03 \x01(\fR\x05crypt\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\fR\x04meta\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"event_time\x18\x06 \x01(\x03R\teventTime\"Z\n" +
	"\x13SecretDeleteRequest\x12$\n" +
	"\x04auth\x18\x01 \x01(\v2\x10.gophkeeper.AuthR\x04auth\x12\x1d\n" +
	"\n" +
	"event_time\x18\x02 \x01(\x03R\teventTime\"{\n" +
	"\vSecretEvent\x120\n" +
	"\x06action\x18\x01 \x01(\x0e2\x18.gophkeeper.SecretActionR\x06action\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12*\n" +
	"\x06secret\x18\x03 \x01(\v2\x12.gophkeeper.SecretR\x06secret*>\n" +
	"\fSecretAction\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04LIST\x10\x01\x12\n" +
	"\n" +
	"\x06STORED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x032\xc2\x01\n" +
	"\rSecretService\x12;\n" +
	"\x05Store\x12\x1e.gophkeeper.SecretStoreRequest\x1a\x12.gophkeeper.Secret\x12=\n" +
	"\x06Delete\x12\x1f.gophkeeper.SecretDeleteRequest\x1a\x12.gophkeeper.Secret\x125\n" +
	"\x06Stream\x12\x10.gophkeeper.Auth\x1a\x17.gophkeeper.SecretEvent0\x01B\rZ\v./pkg/protob\x06proto3"

var (
	file_api_proto_secret_proto_rawDescOnce sync.Once
	file_api_proto_secret_proto_rawDescData []byte
)

func file_api_proto_secret_proto_rawDescGZIP() []byte {
	file_api_proto_secret_proto_rawDescOnce.Do(func() {
		file_api_proto_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_secret_proto_rawDesc), len(file_api_proto_secret_proto_rawDesc)))
	})
	return file_api_proto_secret_proto_rawDescData
}

var file_api_proto_secret_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_secret_proto_goTypes = []any{
	(SecretAction)(0),           // 0: gophkeeper.SecretAction
	(*Auth)(nil),                // 1: gophkeeper.Auth
	(*Secret)(nil),              // 2: gophkeeper.Secret
	(*SecretStoreRequest)(nil),  // 3: gophkeeper.SecretStoreRequest
	(*SecretDeleteRequest)(nil), // 4: gophkeeper.SecretDeleteRequest
	(*SecretEvent)(nil),         // 5: gophkeeper.SecretEvent
}
var file_api_proto_secret_proto_depIdxs = []int32{
	1, // 0: gophkeeper.SecretStoreRequest.auth:type_name -> gophkeeper.Auth
	1, // 1: gophkeeper.SecretDeleteRequest.auth:type_name -> gophkeeper.Auth
	0, // 2: gophkeeper.SecretEvent.action:type_name -> gophkeeper.SecretAction
	2, // 3: gophkeeper.SecretEvent.secret:type_name -> gophkeeper.Secret
	3, // 4: gophkeeper.SecretService.Store:input_type -> gophkeeper.SecretStoreRequest
	4, // 5: gophkeeper.SecretService.Delete:input_type -> gophkeeper.SecretDeleteRequest
	1, // 6: gophkeeper.SecretService.Stream:input_type -> gophkeeper.Auth
	2, // 7: gophkeeper.SecretService.Store:output_type -> gophkeeper.Secret
	2, // 8: gophkeeper.SecretService.Delete:output_type -> gophkeeper.Secret
	5, // 9: gophkeeper.SecretService.Stream:output_type -> gophkeeper.SecretEvent
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_secret_proto_init() }
func file_api_proto_secret_proto_init() {
	if File_api_proto_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_secret_proto_rawDesc), len(file_api_proto_secret_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_secret_proto_goTypes,
		DependencyIndexes: file_api_proto_secret_proto_depIdxs,
		EnumInfos:         file_api_proto_secret_proto_enumTypes,
		MessageInfos:      file_api_proto_secret_proto_msgTypes,
	}.Build()
	File_api_proto_secret_proto = out.File
	file_api_proto_secret_proto_goTypes = nil
	file_api_proto_secret_proto_depIdxs = nil
}
